const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Text: 0},
	{實體: 0},
	{主頁按鈕: 0},
	{background2: 0},
	{Q1: 0},
	{"9patch": 0},
	{Touch: 0},
	{學術性: 0},
	{團體性: 0},
	{行政性: 0},
	{音樂性: 0},
	{Sprite: 0},
	{t1: 0},
	{t2: 0},
	{music: 0},
	{行政: 0},
	{答對: 0},
	{"9patch2": 0},
	{Text2: 0},
	{"9patch3": 0},
	{學適性介紹: 0},
	{滑鼠: 0},
	{行政1: 0},
	{行政3: 0},
	{團體對話: 0},
	{團替介紹: 0},
	{next: 0},
	{"9patch4": 0},
	{"9patch5": 0},
	{Text3: 0},
	{"9patch6": 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{"9patch7": 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Text8: 0},
	{圈圈1: 0},
	{勾勾: 0},
	{參與執行: 0},
	{"9patch8": 0},
	{"9patch9": 0},
	{Text9: 0},
	{網站: 0},
	{Browser: 0},
	{"9patch10": 0},
	{"9patch11": 0}
];

self.InstanceType = {
	background: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	主頁按鈕: class extends self.ISpriteInstance {},
	background2: class extends self.ITiledBackgroundInstance {},
	Q1: class extends self.ITextInstance {},
	_9patch: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	學術性: class extends self.ITextInstance {},
	團體性: class extends self.ITextInstance {},
	行政性: class extends self.ITextInstance {},
	音樂性: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	t1: class extends self.ISpriteInstance {},
	t2: class extends self.IWorldInstance {},
	music: class extends self.IWorldInstance {},
	行政: class extends self.IWorldInstance {},
	答對: class extends self.IInstance {},
	_9patch2: class extends self.IWorldInstance {},
	Text2: class extends self.ITextInstance {},
	_9patch3: class extends self.IWorldInstance {},
	學適性介紹: class extends self.ITextInstance {},
	滑鼠: class extends self.IInstance {},
	行政1: class extends self.IWorldInstance {},
	行政3: class extends self.ITextInstance {},
	團體對話: class extends self.IWorldInstance {},
	團替介紹: class extends self.ITextInstance {},
	next: class extends self.ISpriteInstance {},
	_9patch4: class extends self.IWorldInstance {},
	_9patch5: class extends self.IWorldInstance {},
	Text3: class extends self.ITextInstance {},
	_9patch6: class extends self.IWorldInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	_9patch7: class extends self.IWorldInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	圈圈1: class extends self.IWorldInstance {},
	勾勾: class extends self.IWorldInstance {},
	參與執行: class extends self.ITextInstance {},
	_9patch8: class extends self.IWorldInstance {},
	_9patch9: class extends self.IWorldInstance {},
	Text9: class extends self.ITextInstance {},
	網站: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	_9patch10: class extends self.IWorldInstance {},
	_9patch11: class extends self.IWorldInstance {}
}